name: Build site

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build Vuepress 🔧
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 升級到 v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4 # 升級到 v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 目前最新版本是 v3，非 v4，保持最新
        with:
          path: 'docs/.vuepress/dist'
        
      - name: Deploy & update
        id: deployment
        uses: peaceiris/actions-gh-pages@v4 # 此 action 目前仍為 v3，未有 v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'docs/.vuepress/dist'
          publish_branch: gh-pages
          
  Deploy:
    name: Deploy to Github Pages 🚀
    runs-on: ubuntu-latest
    needs: Build
    
    permissions:
      id-token: write
      pages: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 升級到 v4
